### ISSUE TITLE
Add Data storage and Networking Conversions

### ISSUE THREAD

**Issue by vallamost** [tinytacoteam/zazu-calculator#5]
It'd be nice to be able to calculate data storage and networking values, e.g.:

100 MB / 3Mbps = the time it would take to download 100MBs at 3Mbps. ~ 4.4 Minutes

16128283 Bytes to KB = 16128.283

**Comment by afaur** [comment]
Looks like this can be done currently.

The question you have to ask isn't pretty, and the response could use some work as well.

<img width="602" alt="calc-download-time" src="https://user-images.githubusercontent.com/898523/28291678-595fd356-6b00-11e7-8487-1fe8cd0e356e.png">

<img width="602" alt="calc-bytes-to-kilobytes" src="https://user-images.githubusercontent.com/898523/28291997-0fecce8e-6b02-11e7-8ea8-52244ea1cbfe.png">

Could capture the input using a regex (based on the desired question format). Then pass the extracted important values across.

Its also possible to alter aliases for defined `units` which might allow a better abbreviation to be used for the [units](http://mathjs.org/docs/datatypes/units.html#userdefined-units)
